# Generated by Django 5.1.1 on 2024-10-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_mealcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealcard",
            name="month",
            field=models.CharField(
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                default="October",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="mealcard",
            name="year",
            field=models.IntegerField(default=2024),
        ),
    ]
