# Generated by Django 5.1.1 on 2024-10-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_mealcard_month_mealcard_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="guardian_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
