# Generated by Django 5.1.1 on 2024-10-27 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostels", "0004_hostel_hostelroom_hostel"),
        ("students", "0007_student_room_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="hostel_assigned",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hostelstudents",
                to="hostels.hostel",
            ),
        ),
    ]
