# Generated by Django 5.1.1 on 2024-10-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealcardpayment",
            name="transaction_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rentpayment",
            name="transaction_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
