# Generated by Django 5.1.1 on 2024-10-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_mealcardpayment_transaction_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealcardpayment",
            name="card_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
