# Generated by Django 5.1.1 on 2024-10-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_mealcardpayment_card_number"),
        ("students", "0004_mealcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealcardpayment",
            name="mealcard",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.mealcard",
            ),
        ),
    ]
