# Generated by Django 5.1.1 on 2024-10-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(default="1999-10-10"),
        ),
    ]
