# Generated by Django 5.1.1 on 2024-10-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=255
                    ),
                ),
                ("phone_number", models.CharField(max_length=255)),
                ("guardian_name", models.CharField(max_length=255)),
                ("guardian_phone_number", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=255)),
                ("mpesa_code", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
