# Generated by Django 5.1.1 on 2024-10-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostels", "0002_booking_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostelRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("room_number", models.CharField(max_length=255)),
                ("room_capacity", models.IntegerField(default=1)),
                ("students_assigned", models.IntegerField(default=0)),
                ("fully_booked", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
