# Generated by Django 5.1.1 on 2024-10-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostels", "0004_hostel_hostelroom_hostel"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="room_assigned",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hostels.hostelroom",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Confirmed", "Confirmed"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
